export const ACTION_ADD = 'post:add'
export const ACTION_PIN = 'post:pin'
export const ACTION_NAMEPUBLISH = 'post:namePublish'
export const ACTION_KEYGENERATE = 'post:keyGenerate'
export const ACTION_KEYLIST = 'post:keyList'
